/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package core;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {

  private App app;

  @BeforeEach
  public void setUp() throws Exception {
    this.app = new App();
  }

  // Test app constructor
  @Test 
  public void testConstruction() {
    assertNotNull(app);
  }

}
